[tasks.init]
extends = "tg:init"

[tasks.plan]
extends = "tg:plan"

[tasks.apply]
extends = "tg:apply"
wait_for = [
  "//deployment/modules/talos/cluster:apply",
  "//deployment/modules/netbird/cluster:apply",
]

[tasks.destroy]
extends = "tg:destroy"

[tasks.output]
extends = "tg:output"
