---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vmuser-remote-cluster-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-environment
  target:
    name: vmuser-remote-cluster-token
    template:
      data:
        token: "{{ .password }}"
  dataFrom:
    - extract:
        key: VICTORIAMETRICS_VMAUTH_PASSWORD
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/operator.victoriametrics.com/vmuser_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: remote-clusters
spec:
  tokenRef:
    name: vmuser-remote-cluster-token
    key: token
  targetRefs:
    - static:
        url: http://vminsert-victoria-metrics.o11y.svc.cluster.local:8480
      paths:
        - /insert/0/.*
    - static:
        url: http://victoria-logs-vlinsert.o11y.svc.cluster.local:9481
      paths:
        - /insert/jsonline
        - /insert/native
        - /insert/elasticsearch/.*
        - /insert/loki/.*
        - /insert/opentelemetry/.*
