---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-postgres-superuser-password
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-environment
  target:
    name: grafana-postgres-superuser-password
    template:
      type: kubernetes.io/basic-auth
      data:
        username: postgres
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: GRAFANA_POSTGRES_SUPERUSER_PASSWORD
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-postgres-password
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-environment
  target:
    name: grafana-postgres-password
    template:
      type: kubernetes.io/basic-auth
      data:
        username: grafana
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: GRAFANA_POSTGRES_PASSWORD
