apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs-collector
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-logs-collector
  interval: 1h
  values:
    remoteWrite:
      - url: http://victoria-logs-victoria-logs-single-server-0.victoria-logs-victoria-logs-single-server.o11y.svc.cluster.local:9428
