---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cert-manager-webhook-ovh
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.9.14
    digest: sha256:14cc1ebe829bee748b615c1d2656f744a2ecb1b4899d11f7672964090dacc786
  url: oci://ghcr.io/aureq/charts/cert-manager-webhook-ovh
