---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./prometheus-operator-crds.yaml
  - ./grafana-operator.yaml
  - ./grafana-postgres.yaml
  - ./grafana.yaml
  - ./yucca-o11y.yaml
  - ./victoria-metrics.yaml
  - ./victoria-metrics-users.yaml
  - ./victoria-logs.yaml
  - ./victoria-logs-collector.yaml
  - ./namespace.yaml
