---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  CLUSTER_APP_DOMAIN: staging.futostatus.com
  # Bootstrap-cluster-owned opc VIP (not o11y TF, hence not in bootstrap-settings).
  CLUSTER_OPC_VIP: 10.41.19.250
  CLUSTER_NAME: o11y-staging
  CLUSTER_OP_O11Y_VAULT: o11y_tf_staging
  CLUSTER_OP_SHARED_VAULT: shared_tf_staging
  CLUSTER_VMLOGS_RETENTION: 30d
  CLUSTER_VMLOGS_STORAGE_CLASS: openebs-spare-disk
  CLUSTER_VMETRICS_RETENTION: 30d
