---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  APP_DOMAIN: staging.futostatus.com
  CLUSTER_NAME: o11y-staging
  OP_VAULT: o11y_tf_staging
  LOGS_RETENTION_PERIOD: 30d
  LOGS_STORAGE_CLASS: openebs-spare-disk
  METRICS_RETENTION_PERIOD: 30d
