---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/descheduler
  - ../../base/metrics-server
  - ../../base/multus-networks
  - ../../base/multus
  - ../../base/reloader
  - ../../base/spegel
  - ./namespace.yaml
components:
  - ../../../components/replacements
patches:
  - path: patches/descheduler.yaml
  - path: patches/metrics-server.yaml
  - path: patches/reloader.yaml
  - path: patches/spegel.yaml
