---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-logs
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.2.8
    digest: sha256:7d20ea18d8513e77aacc83fcc620562357725754452e7fdf02091e206615484e
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-logs-cluster
