---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  patches:
    - patch: |-
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: OCIRepository
        metadata:
          name: envoy-gateway
        spec:
          ref:
            # renovate: datasource=docker depName=mirror.gcr.io/envoyproxy/gateway-helm
            tag: v1.8.3
            digest: sha256:cfb34ff4266c87a394cd6be5c13607a2dd47083aef771368302eaeaa99c4a0a9
      target:
        kind: OCIRepository
        name: envoy-gateway
