---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  patches:
    - patch: |-
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: OCIRepository
        metadata:
          name: external-secrets
        spec:
          ref:
            # renovate: datasource=docker depName=ghcr.io/external-secrets/charts/external-secrets
            tag: 2.8.0
            digest: sha256:8649e47ebbf0d4b1ae76c0384c4b9a44b1d4f502176c76b7694757b2adae9970
      target:
        kind: OCIRepository
        name: external-secrets
