---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  patches:
    - patch: |-
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: OCIRepository
        metadata:
          name: external-secrets
        spec:
          ref:
            # renovate: datasource=docker depName=ghcr.io/external-secrets/charts/external-secrets
            tag: 2.2.0
            digest: sha256:feb252e996e2ce31ea015a1e098f2c5d438389a0a2fc1f43659b3f5421046f6f
      target:
        kind: OCIRepository
        name: external-secrets
