---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  patches:
    - patch: |-
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: OCIRepository
        metadata:
          name: external-secrets
        spec:
          ref:
            # renovate: datasource=docker depName=ghcr.io/external-secrets/charts/external-secrets
            tag: 2.10.0
            digest: sha256:09c65bc51967e5bca9aa295e196d365f843eceb3be5600ef77f279ff814b6af2
      target:
        kind: OCIRepository
        name: external-secrets
