---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-webhook
spec:
  chartRef:
    kind: OCIRepository
    name: cert-manager-webhook
  interval: 1h
  values:
    groupName: acme.futostat.us
    issuers:
      - name: letsencrypt
        create: true
        kind: ClusterIssuer
        acmeServerUrl: https://acme-v02.api.letsencrypt.org/directory
        email: acme@futostat.us
        ovhEndpointName: ovh-eu
        ovhAuthenticationMethod: application
        ovhAuthenticationRef:
          applicationKeyRef:
            name: ovh-credentials
          applicationSecretRef:
            name: ovh-credentials
          applicationConsumerKeyRef:
            name: ovh-credentials
