---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vmuser-remote-cluster-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-shared-environment
  target:
    name: vmuser-remote-cluster-token
    template:
      data:
        token: "{{ .password }}"
  dataFrom:
    - extract:
        key: O11Y_VICTORIAMETRICS_VMAUTH_PASSWORD
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/operator.victoriametrics.com/vmuser_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: remote-clusters
spec:
  tokenRef:
    name: vmuser-remote-cluster-token
    key: token
  targetRefs:
    - static:
        url: http://vminsert-victoria-metrics.o11y.svc.cluster.local:8480/insert/multitenant
      paths:
        - /insert/0/.*
      drop_src_path_prefix_parts: 2
    - static:
        url: http://vmauth-victoria-logs.o11y.svc.cluster.local:8427
      paths:
        - /insert/jsonline
        - /insert/native
        - /insert/elasticsearch/.*
        - /insert/loki/.*
        - /insert/opentelemetry/.*
    - static:
        url: http://vmselect-victoria-metrics.o11y.svc.cluster.local:8481/select/multitenant
      paths:
        - /select/0/.*
      drop_src_path_prefix_parts: 2
    - static:
        url: http://vmauth-victoria-logs.o11y.svc.cluster.local:8427
      paths:
        - /select/logsql/.*
