---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openebs
  namespace: flux-system
spec:
  patches:
    - patch: |-
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: OCIRepository
        metadata:
          name: openebs
        spec:
          ref:
            # renovate: datasource=docker depName=ghcr.io/openebs/charts/openebs
            tag: 4.5.1
            digest: sha256:b74c651822ed1811360936bec24d2ee0fc073c1def1098e2399fd7de76c63dca
      target:
        kind: OCIRepository
        name: openebs
