---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openebs
  namespace: flux-system
spec:
  patches:
    - patch: |-
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: OCIRepository
        metadata:
          name: openebs
        spec:
          ref:
            # renovate: datasource=docker depName=ghcr.io/openebs/charts/openebs
            tag: 4.6.1
            digest: sha256:7e22babd055db1058f4325e6e13230eb75945f3623ceb71b4d2060ffab4ba379
      target:
        kind: OCIRepository
        name: openebs
