---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-metrics-stack
  namespace: flux-system
spec:
  targetNamespace: o11y
  dependsOn:
    - name: victoria-metrics-operator
    - name: openebs
  interval: 1h
  path: ./kubernetes/apps/o11y/victoria-metrics-stack/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: vm-zone-endpoints
        optional: false
