---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-logs-mcp
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.1.0
    digest: sha256:7f34dc5f71990b78ef7a781d5a602f453caf4b1b851bfb4350a423803e32fb49
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-logs-mcp
