---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/grafana.integreatly.org/grafana_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: grafana
spec:
  config:
    analytics:
      check_for_updates: "false"
      check_for_plugin_updates: "false"
      feedback_links_enabled: "false"
      reporting_enabled: "false"
    auth:
      disable_login_form: "true"
      oauth_allow_insecure_email_lookup: "true"
    auth.anonymous:
      enabled: "false"
    auth.basic:
      enabled: "false"
    auth.generic_oauth:
      enabled: "true"
      name: Zitadel
      client_secret: ""
      use_pkce: "true"
      scopes: openid email profile groups offline_access
      auth_url: https://auth.internal.futo.org/oauth/v2/authorize
      token_url: https://auth.internal.futo.org/oauth/v2/token
      api_url: https://auth.internal.futo.org/oidc/v1/userinfo
      role_attribute_path: role
      allow_assign_grafana_admin: "true"
      auto_login: "true"
    log:
      mode: console
    metrics:
      enabled: "true"
    news:
      news_feed_enabled: "false"
    plugins:
      plugin_admin_enabled: "false"
    security:
      angular_support_enabled: "true"
    server:
      enable_gzip: "true"
      root_url: https://grafana.${APP_DOMAIN}
    database:
      type: postgres
      host: grafana-postgres-rw.o11y.svc.cluster.local:5432
      name: grafana
      user: grafana
      ssl_mode: require
  deployment:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      replicas: 3
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 0
          maxUnavailable: 1
      template:
        spec:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app: grafana
          containers:
            - name: grafana
              env:
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: grafana-admin-password
                      key: GF_SECURITY_ADMIN_PASSWORD
                - name: GF_DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: grafana-postgres-password
                      key: password
                - name: GF_SECURITY_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: grafana-secret-key
                      key: GF_SECURITY_SECRET_KEY
                - name: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: grafana-oauth
                      key: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities: {drop: ["ALL"]}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
          volumes:
            - name: grafana-data
              emptyDir: {}
  httpRoute:
    spec:
      hostnames:
        - grafana.${APP_DOMAIN}
      parentRefs:
        - name: envoy
          namespace: envoy-system
  disableDefaultSecurityContext: All
