---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./grafana.yaml
  - ./datasource.yaml
  - ./contactpoint-discord.yaml
  - ./notificationpolicy.yaml
  - ./alerts-o11y.yaml
  - ./dashboards
