---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: echo
  namespace: flux-system
spec:
  patches:
    - patch: |-
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: OCIRepository
        metadata:
          name: echo
        spec:
          ref:
            # renovate: datasource=docker depName=ghcr.io/home-operations/charts/echo
            tag: 0.2.2
            digest: sha256:d9459d98127252635791dd85fdfb0479d64b8501c4c9dd935a47dc41d141c4fd
      target:
        kind: OCIRepository
        name: echo
