apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: storage
spec:
  chartRef:
    kind: OCIRepository
    name: openebs
  interval: 1h
  values:
    localpv-provisioner:
      localpv:
        basePath: &hostPath /var/mnt/u-hostpath
        replicas: 1
        enableLeaderElection: true
        requests:
          cpu: 20m
          memory: 64Mi
        limits:
          memory: 128Mi

      hostpathClass:
        enabled: true
        name: openebs-hostpath
        reclaimPolicy: Delete
        isDefaultClass: true
        basePath: *hostPath

    analytics:
      enabled: false
    alloy:
      enabled: false
    loki:
      enabled: false
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: false
    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: false
          keep: false
