---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: echo
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.2.2
    digest: sha256:d9459d98127252635791dd85fdfb0479d64b8501c4c9dd935a47dc41d141c4fd
  url: oci://ghcr.io/home-operations/charts/echo
