---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  APP_DOMAIN: futostatus.com
  CLUSTER_NAME: o11y-production
  OP_VAULT: o11y_tf_prod
  LOGS_RETENTION_PERIOD: 120d
  LOGS_STORAGE_CLASS: openebs-spare-disk-2
  METRICS_RETENTION_PERIOD: 120d
