apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-logs-single
  interval: 1h
  values:
    server:
      resources:
        limits:
          cpu: 4
          memory: 8Gi
        requests:
          cpu: 4
          memory: 8Gi
      persistentVolume:
        size: 100Gi
      ingress:
        enabled: true
        hosts:
          # TODO: inject tailscale hostname
          - name: localhost
            path:
              - /logs/
        ingressClassName: nginx
    dashboards:
      enabled: true
      grafanaOperator:
        enabled: true
