---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: prometheus-operator-crds
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: grafana-operator
      namespace: o11y
  interval: 1h
  path: ./kubernetes/apps/base/grafana-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: o11y
  patches:
    - patch: |-
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: OCIRepository
        metadata:
          name: grafana-operator
        spec:
          ref:
            # renovate: datasource=docker depName=ghcr.io/grafana/helm-charts/grafana-operator
            tag: 5.24.0
            digest: sha256:4f69cdaecfed2cc61d4e5f4a8e7142795e9b00997e4bcbd37a8c154a225a2f1f
      target:
        kind: OCIRepository
        name: grafana-operator
