---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/yucca-o11y
  - ../../base/prometheus-operator-crds
  - ../../base/grafana-operator
  - ../../base/grafana-postgres
  - ../../base/grafana
  - ../../base/victoria-metrics
  - ../../base/victoria-metrics-users
  - ../../base/victoria-logs
  - ../../base/victoria-logs-collector
  - ../../base/gatus-sidecar
  - ./namespace.yaml
components:
  - ../../../components/replacements
patches:
  - path: patches/prometheus-operator-crds.yaml
  - path: patches/grafana-operator.yaml
  - path: patches/grafana-postgres.yaml
  - path: patches/victoria-metrics.yaml
  - path: patches/victoria-logs.yaml
  - path: patches/victoria-logs-collector.yaml
