---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-logs
  namespace: flux-system
spec:
  dependsOn:
    - name: victoria-metrics
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: victoria-logs
      namespace: o11y
  interval: 1h
  path: ./kubernetes/apps/base/victoria-logs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: o11y
  patches:
    - patch: |-
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: OCIRepository
        metadata:
          name: victoria-logs
        spec:
          ref:
            # renovate: datasource=docker depName=ghcr.io/victoriametrics/helm-charts/victoria-logs-cluster
            tag: 0.2.7
            digest: sha256:40d8bb343ee8ecb421e762f9c5b3366ce1a23dc30259ad3374ab70c258d34f8e
      target:
        kind: OCIRepository
        name: victoria-logs
