---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-logs-collector
  namespace: flux-system
spec:
  dependsOn:
    - name: victoria-logs
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: victoria-logs-collector
      namespace: o11y
  interval: 1h
  path: ./kubernetes/apps/base/victoria-logs-collector
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: o11y
  patches:
    - patch: |-
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: OCIRepository
        metadata:
          name: victoria-logs-collector
        spec:
          ref:
            # renovate: datasource=docker depName=ghcr.io/victoriametrics/helm-charts/victoria-logs-collector
            tag: 0.3.6
            digest: sha256:6b7d73c14e1fb20c24bf5cb13880575f13572961560f60be504f256de3497659
      target:
        kind: OCIRepository
        name: victoria-logs-collector
