---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  patches:
    - patch: |-
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: OCIRepository
        metadata:
          name: cert-manager
        spec:
          ref:
            # renovate: datasource=docker depName=quay.io/jetstack/charts/cert-manager
            tag: v1.21.1
            digest: sha256:15c0b46d9006ce8eb9ff14d1bf54d1bbfcc587bb9e24cd9fe186fb8fec56af1f
      target:
        kind: OCIRepository
        name: cert-manager
