---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cert-manager-webhook-ovh
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.9.16
    digest: sha256:eaebc18fc4a6acd07b8bf48e91f588838da90da9b5bd9032ea3db742ab5330eb
  url: oci://ghcr.io/aureq/charts/cert-manager-webhook-ovh
