---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cert-manager-webhook-ovh
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.9.15
    digest: sha256:cc5bdee12395ad88f88bb194e383ec7fac9b07cde05e35bae34ee88d858e4bbb
  url: oci://ghcr.io/aureq/charts/cert-manager-webhook-ovh
