---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./descheduler.yaml
  - ./metrics-server.yaml
  - ./multus.yaml
  - ./multus-networks.yaml
  - ./namespace.yaml
  - ./reloader.yaml
  - ./spegel.yaml
