---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-password
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-environment
  target:
    name: grafana-admin-password
    template:
      data:
        GF_SECURITY_ADMIN_PASSWORD: "{{ .password }}"
  dataFrom:
    - extract:
        key: GRAFANA_ADMIN_PASSWORD
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secret-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-environment
  target:
    name: grafana-secret-key
    template:
      data:
        GF_SECURITY_SECRET_KEY: "{{ .password }}"
  dataFrom:
    - extract:
        key: GRAFANA_SECRET_KEY
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oauth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-shared
  target:
    name: grafana-oauth
  data:
    - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
      remoteRef:
        key: FUTO_ZITADEL_OAUTH_CLIENT_ID_GRAFANA_O11Y
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-discord-webhook
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-environment
  target:
    name: grafana-discord-webhook
    template:
      data:
        url: "{{ .password }}"
  dataFrom:
    - extract:
        key: GRAFANA_DISCORD_WEBHOOK
