---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./vmuser-external-write.yaml
  - ./vmuser-external-read.yaml
  - ./vmuser-internal-write.yaml
  - ./vmuser-internal-read.yaml
