---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: internal-read
  namespace: o11y
  labels:
    type: internal
spec:
  username: "reader"
  passwordRef:
    name: vmauth-internal-credentials
    key: reader-password

  targetRefs:
    - crd:
        kind: VMSingle
        name: vmsingle
        namespace: o11y
      paths:
        - "/api/v1/query"
        - "/api/v1/query_range"
        - "/api/v1/series"
        - "/api/v1/labels"
        - "/api/v1/label/.*/values"
        - "/prometheus/api/v1/.*"

  retry_status_codes: [429, 500, 502, 503, 504]
