---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: internal-write
  namespace: o11y
  labels:
    type: internal
spec:
  username: "writer"
  passwordRef:
    name: vmauth-internal-credentials
    key: writer-password

  targetRefs:
    - crd:
        kind: VMSingle
        name: vmsingle
        namespace: o11y
      target_path_suffix: "/api/v1/write"
      paths:
        - "/api/v1/write"

  retry_status_codes: [429, 500, 502, 503, 504]
