---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus-operator-crds
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 27.0.1
    digest: sha256:1f589fac8c0844cc8850c867820004d4549c0e269e54f2658c7a22f01f0f3501
  url: oci://ghcr.io/prometheus-community/charts/prometheus-operator-crds
