---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-operator
  namespace: flux-system
spec:
  patches:
    - patch: |-
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: OCIRepository
        metadata:
          name: grafana-operator
        spec:
          ref:
            # renovate: datasource=docker depName=ghcr.io/grafana/helm-charts/grafana-operator
            tag: 5.25.0
            digest: sha256:ae311e8675c11a1d12112eb45676415a797f9dfb7eee91b82f422b53d7c7ab6d
      target:
        kind: OCIRepository
        name: grafana-operator
