---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-operator-crds
  namespace: flux-system
spec:
  patches:
    - patch: |-
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: OCIRepository
        metadata:
          name: prometheus-operator-crds
        spec:
          ref:
            # renovate: datasource=docker depName=ghcr.io/prometheus-community/charts/prometheus-operator-crds
            tag: 31.0.1
            digest: sha256:45a18cd10ce5c57cbcdd90e4eddfa9a6f653684a8d74cf6b2925f682c8a023e5
      target:
        kind: OCIRepository
        name: prometheus-operator-crds
