---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-operator-crds
  namespace: flux-system
spec:
  patches:
    - patch: |-
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: OCIRepository
        metadata:
          name: prometheus-operator-crds
        spec:
          ref:
            # renovate: datasource=docker depName=ghcr.io/prometheus-community/charts/prometheus-operator-crds
            tag: 31.0.0
            digest: sha256:1632a0e96a3047b0761685378e3a63f9f8a21ff7e567920323eb66d8c438c5c0
      target:
        kind: OCIRepository
        name: prometheus-operator-crds
