---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-metrics
  namespace: flux-system
spec:
  patches:
    - patch: |-
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: OCIRepository
        metadata:
          name: victoria-metrics
        spec:
          ref:
            # renovate: datasource=docker depName=ghcr.io/victoriametrics/helm-charts/victoria-metrics-k8s-stack
            tag: 0.90.0
            digest: sha256:090817973bfd91766806532e36c7f5cb1a7c5b04f6b89192572bfc62785918d2
      target:
        kind: OCIRepository
        name: victoria-metrics
