---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-logs-collector
  namespace: flux-system
spec:
  patches:
    - patch: |-
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: OCIRepository
        metadata:
          name: victoria-logs-collector
        spec:
          ref:
            # renovate: datasource=docker depName=ghcr.io/victoriametrics/helm-charts/victoria-logs-collector
            tag: 0.3.7
            digest: sha256:2ec5d41cbc0309ef0cfa10945e5b7773298ba25b8a67a28296f888b8adb2b0ba
      target:
        kind: OCIRepository
        name: victoria-logs-collector
