---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-metrics
  namespace: flux-system
spec:
  patches:
    - patch: |-
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: OCIRepository
        metadata:
          name: victoria-metrics
        spec:
          ref:
            # renovate: datasource=docker depName=ghcr.io/victoriametrics/helm-charts/victoria-metrics-k8s-stack
            tag: 0.90.2
            digest: sha256:c8891917df7d3605f5930ba657560e9bdaf818a997fcd567286e06eb2cdd25fd
      target:
        kind: OCIRepository
        name: victoria-metrics
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: victoria-metrics
        spec:
          values:
            vmcluster:
              spec:
                vmstorage:
                  resources:
                    requests:
                      memory: 8Gi
                    limits:
                      memory: 48Gi
                vmselect:
                  resources:
                    requests:
                      memory: 2Gi
                    limits:
                      memory: 32Gi
                  extraArgs:
                    search.maxConcurrentRequests: "8"
      target:
        kind: HelmRelease
        name: victoria-metrics
