---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victoria-logs
  namespace: flux-system
spec:
  patches:
    - patch: |-
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: OCIRepository
        metadata:
          name: victoria-logs
        spec:
          ref:
            # renovate: datasource=docker depName=ghcr.io/victoriametrics/helm-charts/victoria-logs-cluster
            tag: 0.2.8
            digest: sha256:7d20ea18d8513e77aacc83fcc620562357725754452e7fdf02091e206615484e
      target:
        kind: OCIRepository
        name: victoria-logs
