---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
replacements:
  - source:
      kind: Namespace
      fieldPath: metadata.name
    targets:
      - select:
          group: kustomize.toolkit.fluxcd.io
          kind: Kustomization
        fieldPaths:
          - spec.targetNamespace
        options:
          create: true
