---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: netbird-router
  namespace: flux-system
spec:
  patches:
    - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: netbird-router
        spec:
          template:
            spec:
              containers:
                - name: netbird
                  # renovate: datasource=docker depName=netbirdio/netbird
                  image: netbirdio/netbird:0.76.3@sha256:9f0ad6ae354359926adbd40735fc2cb0be75c786759492abb160a1170544970b
      target:
        kind: Deployment
        name: netbird-router
