---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: netbird-router
  namespace: flux-system
spec:
  patches:
    - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: netbird-router
        spec:
          template:
            spec:
              containers:
                - name: netbird
                  # renovate: datasource=docker depName=netbirdio/netbird
                  image: netbirdio/netbird:0.78.1@sha256:c0b492f320e1251ac0655e785fa288e935a0b7b16365d14fdcbc8bf75dc5b0a0
      target:
        kind: Deployment
        name: netbird-router
