---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/openebs
  - ./namespace.yaml
  - ./storageclass-spare-disk-2.yaml
components:
  - ../../../components/replacements
patches:
  - path: patches/openebs.yaml
