---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  patches:
    - patch: |-
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: OCIRepository
        metadata:
          name: metrics-server
        spec:
          ref:
            # renovate: datasource=docker depName=ghcr.io/home-operations/charts-mirror/metrics-server
            tag: 3.13.1
            digest: sha256:9dfceeb7f001232602ab4bdd3fd2e61ac50da7081acf5518910276b7fe3a932d
      target:
        kind: OCIRepository
        name: metrics-server
