---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  patches:
    - patch: |-
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: OCIRepository
        metadata:
          name: metrics-server
        spec:
          ref:
            # renovate: datasource=docker depName=ghcr.io/home-operations/charts-mirror/metrics-server
            tag: 3.14.0
            digest: sha256:8a9ade2972ba4a1d748da6a78a313a770dab81ebc004441b13099a2c4329ffa9
      target:
        kind: OCIRepository
        name: metrics-server
