---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: reloader
  namespace: flux-system
spec:
  patches:
    - patch: |-
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: OCIRepository
        metadata:
          name: reloader
        spec:
          ref:
            # renovate: datasource=docker depName=ghcr.io/stakater/charts/reloader
            tag: 2.2.14
            digest: sha256:31bd8b82ac350078704e233706a21aec1f0906974febf0a1cc4ac1f3b83063f4
      target:
        kind: OCIRepository
        name: reloader
