---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: spegel
  namespace: flux-system
spec:
  patches:
    - patch: |-
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: OCIRepository
        metadata:
          name: spegel
        spec:
          ref:
            # renovate: datasource=docker depName=ghcr.io/spegel-org/helm-charts/spegel
            tag: 0.7.1
            digest: sha256:9efb90dbec90f3ffda195196eaa151cd1a6c2c30d44d59bb2c0853edf08d4430
      target:
        kind: OCIRepository
        name: spegel
