---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/envoy-gateway
  - ../../base/envoy-proxy
  - ../../base/mesh-gateway-network
  - ../../base/mesh-gateway
  - ./namespace.yaml
components:
  - ../../../components/replacements
patches:
  - path: patches/envoy-gateway.yaml
