name: Zizmor

on:
  pull_request:
  push:
    branches: [main]

jobs:
  zizmor:
    name: Zizmor
    uses: immich-app/devtools/.github/workflows/shared-zizmor.yml@e2ad9a025ca6668c5511182405dffbec98db30b0 # main
    permissions:
      actions: read
      contents: read
      security-events: write
